#!/bin/sh
# This file is made available under the terms of the two-clause BSD
# license. See the file COPYING.BSD in the distribution directory for the
# full license text.

lua $(dirname $0)/cowbel-compiler/main.lua -- "$@"

